__include__: [
  './deim_hgnetv2_x_train_dataset_include_1_9_aug768_freeze_backbone_prodigyplus_3groups.yml'
]

output_dir: ./deim_outputs/baselines/deim_hgnetv2_x_train_dataset_include_1_9_aug768_freeze_backbone_prodigyplus_3groups_40e_nostage

epoches: 40

train_dataloader:
  collate_fn:
    stop_epoch: 9999
