__include__: [
  './object365/deim_hgnetv2_x_obj2coco_24e.yml',
  '../dataset/train_dataset_detection.yml'
]

output_dir: ./deim_outputs/deim_hgnetv2_x_train_dataset_tuning

train_dataloader:
  dataset:
    transforms:
      ops:
        - {type: Mosaic, output_size: 320, rotation_range: 10, translation_range: [0.1, 0.1], scaling_range: [0.5, 1.5],
           probability: 1.0, fill_value: 0, use_cache: False, max_cached_images: 50, random_pop: True}
        - {type: RandomPhotometricDistort, p: 0.3}
        - {type: RandomZoomOut, fill: 0}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: RandomHorizontalFlip}
        - {type: Resize, size: [640, 640], }
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
        - {type: ConvertBoxes, fmt: 'cxcywh', normalize: True}
      policy:
        epoch: [2, 12, 20]
        ops: ['Mosaic', 'RandomPhotometricDistort', 'RandomZoomOut']
      mosaic_prob: 0.1

  collate_fn:
    mixup_prob: 0.0
    mixup_epochs: [0, 0]
    stop_epoch: 20
