__include__: [
  './deim_hgnetv2_x_train_dataset_include_1_9_overfit64_noaug_768_freeze_stage1.yml'
]

output_dir: ./deim_outputs/overfit/deim_hgnetv2_x_train_dataset_include_1_9_overfit64_noaug_768_unfreeze_backbone

HGNetv2:
  freeze_stem_only: False
  freeze_at: -1
